name: Trigger Login Ping

on:
  schedule:
    - cron: '*/10 * * * *' # Jalan tiap 10 menit
  workflow_dispatch:

jobs:
  ping_login:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Login URL with Timestamp
        run: |
          # Ambil waktu sekarang (UTC)
          CURRENT_TIME=$(date +'%Y-%m-%d_%H:%M:%S')
          
          # Kirim ke Login PHP kamu
          # Ganti URL dengan domain kamu
          # Kita kirim parameter: ?source=github & time=... & secret=...
          curl -L -X GET "https://weisteriia.gt.tc/index.php?source=github&time=$CURRENT_TIME&secret=kunci_rahasia_ta" \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
          --max-time 30
